version: '3.8'
services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    expose:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
  api:
    container_name: sensors-api
    build:
      context: ./
    image: sensors-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8086:8086"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    links:
      - db

volumes:
  database: