version: '3.8'
services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: $(POSTGRES_USER)
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
      POSTGRES_DB: $(POSTGRES_DB)
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    container_name: sensors-api
    build:
      context: ./
    image: sensors-api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: $(POSTGRES_USER)
      DB_PASSWORD: $(POSTGRES_PASSWORD)
      DB_NAME: $(POSTGRES_DB_NAME)
    links:
      - db
    volumes:
      - './:/src'

volumes:
  db_data: